Permission manager updated with new Navigation
surfstudio/SurfAndroidStandard pull request #15
Opened 2021-03-26 07:29 UTC by Monster-king

Updates:

**Navigation-observer**
- Added new command to request permission
- Added new route to request permission
- Added logic to handle request permission command
- Added getId: String method to ResultRoute interface
- removed BaseRoute typechecking from methods in ScreenResultEmitter and ScreenResultObserver

**Permission**
- Removed PermissionManagerForActivity and PermissionManagerForFragment
- PermissionManager should be used as Singleton
- Added handling for "grant once" permission.

2021-03-29 10:57 UTC, Monster-king commented on ci-internal/JenkinsfilePullRequestJob.groovy
> -def boolean hasChanges = false
А это я не трогал 🤔

2021-04-05 07:42 UTC, ruslansharipov approved these changes

2021-04-05 08:00 UTC, margarita-v commented on ci-internal/JenkinsfilePullRequestJob.groovy
> -def boolean hasChanges = false
скорее всего, нужен мерж с основной веткой, чтобы убрать лишний дифф

2021-04-05 08:32 UTC, margarita-v requested changes

2021-04-05 08:32 UTC, margarita-v commented on navigation/lib-navigation-observer/src/main/java/ru/surfstudio/android/navigation/observer/storage/file/FileRouteStorage.kt
> +            e.printStackTrace()
желательно Logger.e везде вместо printStackTrace

2021-04-05 08:32 UTC, margarita-v commented on permission/RELEASE_NOTES.md
> +* **NO BACKWARD COMPATIBILITY** ANDDEP-1201 removed core-navigation from dependencies, instead user
instead use

2021-04-05 08:32 UTC, margarita-v commented on navigation/RELEASE_NOTES.md
> +* ANDDEP-1201 Added command RequestPermission, added getId for ResultRoute
описать подробно все изменения без обратной совместимости (как минимум ActivityNavigatorWithResult, ActivityNavigatorWithResultFactory)

2021-04-05 08:32 UTC, margarita-v commented on permission/lib-permission/src/main/java/ru/surfstudio/android/core/ui/permission/PermissionManager.kt
> +            if (it) {
кажется здесь больше подойдет when

2021-04-05 08:32 UTC, margarita-v commented on permission/sample/src/main/java/ru/surfstudio/android/permission/sample/screen/main/camera/CameraPermissionRequest.kt
> +        permissionsRationalStr = "Hello motherfucker"
🔥

2021-04-05 08:32 UTC, margarita-v commented on permission/lib-permission/src/main/java/ru/surfstudio/android/core/ui/permission/PermissionManager.kt
> +            .subscribe {}
мб тогда subscribe(), везде. Мне кажется, не стоит оставлять пустые {}

2021-04-05 14:30 UTC, dmitry-kuzmenchuk approved these changes

2021-04-11 16:22 UTC, Monster-king commented on navigation/RELEASE_NOTES.md
> +* ANDDEP-1201 Added command RequestPermission, added getId for ResultRoute
Тут нет изменения без обратной совместимости. Я просто поправил все семплы с где используется новая навигация.

2021-04-11 16:28 UTC, Monster-king commented on permission/sample/src/main/java/ru/surfstudio/android/permission/sample/screen/main/camera/CameraPermissionRequest.kt
> +        permissionsRationalStr = "Hello motherfucker"
Сори, это было только для тестирования :)

2021-04-29 15:40 UTC, margarita-v approved these changes

2021-04-30 11:15 UTC, merged